Td 2
Apozzz/TwoDayIntern pull request #2
Opened 2023-08-04 13:06 UTC by Apozzz

Kodel neleidzia mergint ?

2023-08-07 07:54 UTC, ArnasPetraitis requested changes

2023-08-07 07:54 UTC, ArnasPetraitis commented on dto-module/.gitignore
.gitignore is only needed in root dir of git repository

2023-08-07 07:54 UTC, ArnasPetraitis commented on dto-module/mvnw
unused?

2023-08-07 07:54 UTC, ArnasPetraitis commented on dto-module/mvnw.cmd
unused?

2023-08-07 07:54 UTC, ArnasPetraitis commented on dto-module/pom.xml
> +	<groupId>com.twoday.dto</groupId>
group id and java package should be more distinctive, e.g. one level deeper if company domain is used.
1. com.twoday : domain of company (or product)
2. "blablabla": project/product name (or abreviation) in your case "warehouse-management-system" is quite long, so could be abreviated to "wms" or "warehousems"

2023-08-07 07:54 UTC, ArnasPetraitis commented on shop-module/src/main/java/com/twoday/shop/shopmodule/response/ApiResponse.java
> +    private Object data;
"Object" in ApiResponse does not take use of DTOs in common module - no serialization is done. Lets say we wanted to group products by category before displaying in shop

2023-08-07 07:54 UTC, ArnasPetraitis commented on shop-module/src/main/java/com/twoday/shop/shopmodule/user/DefaultUserService.java
> +                    if (response.getStatus() == HttpStatus.CREATED.value()) {
not a nice way to handle errors

2023-08-07 07:54 UTC, ArnasPetraitis commented on shop-module/src/main/java/com/twoday/shop/shopmodule/warehouse/WarehouseController.java
> +    public Mono<ResponseEntity<ApiResponse>> getProducts(@PathVariable Long id) {
product endpoints should be in ProductController, but getting products from warehouseService is OK, because it represents integration to warehouse application

2023-08-07 07:54 UTC, ArnasPetraitis commented on warehouse-module/src/main/java/com/twoday/warehouse/warehousemodule/product/DefaultProductConverter.java
> +public class DefaultProductConverter implements ProductConverter {
DefaultProductConverter  ("Default") is not a conventional Java naming. I'm not saying it is bad. By this naming I would expect that those Interfaces being implemented multiple times as standard, which is not a case

2023-08-07 07:54 UTC, ArnasPetraitis commented on warehouse-module/src/main/java/com/twoday/warehouse/warehousemodule/product/DefaultProductConverter.java
> +    public ProductDto toDto(Product product) {
just a hint: Look into `BeanUtils.copy...`

2023-08-07 07:54 UTC, ArnasPetraitis commented on warehouse-module/src/main/java/com/twoday/warehouse/warehousemodule/role/Role.java
> +public class Role implements GrantedAuthority{
Roles was not in a task

2023-08-07 07:54 UTC, ArnasPetraitis commented on warehouse-module/src/main/java/com/twoday/warehouse/warehousemodule/user/DefaultUserService.java
> +        return userRepository.findByUsername(username)
User entity could be simple and not implement UserDetails. Conversion to user details could be done here.

2023-08-07 07:54 UTC, ArnasPetraitis commented on warehouse-module/src/main/java/com/twoday/warehouse/warehousemodule/user/UserController.java
> +                    new ApiResponse(HttpStatus.CREATED.value(), "User registered successfully", userDto),
Using ApiResponse looks more overcomplicated then actual benefits it provides

2023-08-07 07:54 UTC, ArnasPetraitis commented on warehouse-module/src/main/java/com/twoday/warehouse/warehousemodule/warehouse/DefaultWarehouseService.java
> +        return warehouseRepository.findAll().stream().map(warehouseConverter::toDto).toList();
streams are more readable when formatted as step per line

2023-08-07 07:54 UTC, ArnasPetraitis commented on warehouse-module/src/main/java/com/twoday/warehouse/warehousemodule/warehouse/DefaultWarehouseService.java
> +        if (warehouse.isPresent()) {
because you are using optional, you can improve this method. somethink like...
`
return  warehouseRepository.findById(id)
     .map(Warehouse::getProducts)
     .flatMap(List::stream)
     .map(productConverter::toDto)
     .orElse(Collections.emptyList())
`

2023-08-07 07:54 UTC, ArnasPetraitis commented on warehouse-module/src/main/java/com/twoday/warehouse/warehousemodule/warehouse/WarehouseController.java
> +                new ApiResponse(HttpStatus.OK.value(), null, warehouseService.getProductsByWarehouseId(id)),
getProductsByWarehouseId should be in products service

2023-08-07 07:54 UTC, ArnasPetraitis commented on warehouse-module/src/main/java/com/twoday/warehouse/warehousemodule/warehouse/WarehouseController.java
> +        } catch (ResourceNotFoundException ex) {
spring-boot has multiple ways to define exceptions handlers, that will prevent code duplication

2023-08-09 07:16 UTC, ArnasPetraitis requested changes

2023-08-09 07:16 UTC, ArnasPetraitis commented on dto-module/pom.xml
> +	<groupId>com.twoday.wms.dto</groupId>
```
	<groupId>com.twoday.wms</groupId>
	<artifactId>dto</artifactId>
```

2023-08-09 07:16 UTC, ArnasPetraitis commented on dto-module/src/main/java/com/twoday/dto/dtomodule/LoginDto.java
> +package com.twoday.dto.dtomodule;
`package com.twoday.wms.dto;`

2023-08-09 07:16 UTC, ArnasPetraitis commented on shop-module/pom.xml
> +	<groupId>com.twoday.wms.shop</groupId>
```
	<groupId>com.twoday.wms</groupId>
	<artifactId>shop</artifactId>
```

2023-08-09 07:16 UTC, ArnasPetraitis commented on shop-module/src/main/java/com/twoday/shop/shopmodule/ShopApplication.java
> +package com.twoday.shop.shopmodule;
```
package com.twoday.wms.shop;
```

2023-08-09 07:16 UTC, ArnasPetraitis commented on shop-module/src/main/java/com/twoday/shop/shopmodule/config/WebClientConfig.java
> +package com.twoday.shop.shopmodule.config;
`package com.twoday.wms.shop.config;`

2023-08-09 07:16 UTC, ArnasPetraitis commented on warehouse-module/pom.xml
> +	<groupId>com.twoday.wms.warehouse</groupId>
```
	<groupId>com.twoday.wms</groupId>
	<artifactId>warehouse</artifactId>
```

2023-08-09 07:16 UTC, ArnasPetraitis commented on warehouse-module/src/main/java/com/twoday/warehouse/warehousemodule/interfaces/GenericConverter.java
> +public interface GenericConverter<T, ID extends Serializable> {
does it have any purpose?

2023-08-09 07:16 UTC, ArnasPetraitis commented on dto-module/pom.xml
> +	<groupId>com.twoday.wms.dto</groupId>
still incorrect :) let me explain why I'm suggesting this: groupId should be same for all project modules (might differ from parent, but also may be the same) and it should define project, in this case `<groupId>com.twoday.wms</groupId>`. next artifact id should have its name, and saying that it is a module are details that has no value, so `<artifactId>dto</artifactId>`

2023-08-09 07:16 UTC, ArnasPetraitis commented on warehouse-module/src/main/java/com/twoday/warehouse/warehousemodule/product/ProductServiceImpl.java
> +        Product product = productRepository.findById(id).orElseThrow(() -> new ResourceNotFoundException("Product not found with id: %s".formatted(id)));
multiple actions in one line are hart to notice. it is more readable if actions are line-breked
```
Product product = productRepository.findById(id)
             .orElseThrow(() -> new ResourceNotFoundException("Product not found with id: %s".formatted(id)));
```

2023-08-10 07:32 UTC, ArnasPetraitis requested changes

2023-08-10 07:32 UTC, ArnasPetraitis commented on warehouse/src/main/java/com/twoday/wms/warehouse/warehouse/WarehouseConverterImpl.java
> +            List<Product> products = productRepository.findAllById(warehouseDto.getProductIds());
if later entity is used for saving only, investigate possibility to set Products without fetching them from db. tip: entity reference

2023-08-10 10:54 UTC, Apozzz commented on warehouse/src/main/java/com/twoday/wms/warehouse/warehouse/WarehouseConverterImpl.java
> +            List<Product> products = productRepository.findAllById(warehouseDto.getProductIds());
Labai idomus dalykas, neteke susidurti, kad zinotu apie entity tik pagal ID :D Ir jei reiktu kazka dar daryti, kad tuomet automatiskai pasiimtu is duombazes, atrodo mazai minusu turintis privalumas.

2023-08-10 11:03 UTC, ArnasPetraitis approved these changes

2023-08-10 12:11 UTC, merged