Td 7 UI
Apozzz/TwoDayIntern pull request #7
Opened 2023-08-18 10:44 UTC by Apozzz

8. Shop UI

a. Susipažinti su:

i. NodeJs,

ii. TypeScript

iii. Angular

iv. HTML/CSS

v. RxJS (Observable)

b. Parduotuvės programoje padaryti Parduotuvės UI

i. Prekių sąrašas

1. Rušiavimas

2. Filtravimas

ii. Prekės puslapis (info ir pardavimo mygtukas)
iv. Pakeisti CSS į SCSS
v. CSS iš npm (bootstrap or etc.)

2023-08-18 11:52 UTC, ArnasPetraitis requested changes

2023-08-18 11:52 UTC, ArnasPetraitis commented on ui/pom.xml
> +	<name>frontend</name>
which frontend? 😀 if only it was named `shop-ui` 🤔

2023-08-18 11:52 UTC, ArnasPetraitis commented on ui/pom.xml
> +                        <id>install node and npm</id>
nice find 👍

2023-08-18 11:52 UTC, ArnasPetraitis commented on .gitignore
> +/dist
if started with `/` it looks from root, and your app is in subfolder, that's why `dist` and `.vscode` was not ignored

2023-08-18 11:52 UTC, ArnasPetraitis commented on ui/src/main/frontend/src/app/components/product-filter/product-filter.component.less
> +mat-slider {
`.` missing?

2023-08-18 11:52 UTC, ArnasPetraitis commented on ui/src/main/frontend/src/app/components/product-filter/product-filter.component.ts
> +      searchName: this.searchName,
should be a type (class)

2023-08-18 11:52 UTC, ArnasPetraitis commented on ui/src/main/frontend/src/app/components/product-list/product-list.component.html
> +            <mat-card-title>ID: {{product.id}}</mat-card-title>
very uncommon to show IDs for user

2023-08-18 11:52 UTC, ArnasPetraitis commented on ui/src/main/frontend/src/app/components/product-sort/product-sort.component.html
> +        <mat-option value="id-asc">ID (Low to High)</mat-option>
sort by name?

2023-08-18 11:52 UTC, ArnasPetraitis commented on ui/src/main/frontend/src/app/components/product-sort/product-sort.component.less
> +        background: #f7f7f7;  // slightly different background for contrast
if less supports variables, maybe extract all colors to common place to  have a consistent look

2023-08-18 11:52 UTC, ArnasPetraitis commented on ui/src/main/frontend/src/app/services/product.service.ts
> +export interface ProductDto {
maybe should be separated to own ts

2023-08-18 11:52 UTC, ArnasPetraitis commented on ui/src/main/frontend/src/index.html
> +  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500&display=swap" rel="stylesheet">
external resources might cause unexpected problems. so usually resources are imported and used from npm

2023-08-18 12:22 UTC, Apozzz commented on ui/src/main/frontend/src/app/components/product-filter/product-filter.component.less
> +mat-slider {
Cia viskas gerai. mat-slider yra elementas, ne klase

2023-08-18 12:23 UTC, Apozzz commented on ui/src/main/frontend/src/app/components/product-sort/product-sort.component.html
> +        <mat-option value="id-asc">ID (Low to High)</mat-option>
Nelabai norejau, kazkaip niekad neteko naudoti ir atrodo nereikalinga(pagal pavadinima). Galiu nebent isimti pagal id.

2023-08-21 11:11 UTC, JustasVit requested changes

2023-08-21 11:11 UTC, JustasVit commented on ui/src/main/frontend/src/app/components/product-list/product-list.component.html
> +      <th>ID</th>
Needs localization

2023-08-21 11:11 UTC, JustasVit commented on ui/src/main/frontend/src/app/components/product-list/product-list.component.html
> +      <th>ID</th>
Do we really want to show ID?

2023-08-22 11:48 UTC, Apozzz commented on ui/src/main/frontend/src/app/components/product-list/product-list.component.html
> +      <th>ID</th>
Localization bus kitam PR :D

2023-08-22 12:13 UTC, JustasVit requested changes

2023-08-22 12:13 UTC, JustasVit commented on shop-ui/src/main/frontend/src/app/components/product-list/product-list.component.less
> +  h1 {
Don't style tags directly, use classes for that.

2023-08-22 12:13 UTC, JustasVit commented on shop-ui/src/main/frontend/src/app/components/product-filter/product-filter.component.less
> +    width: @filter-input-width;
Create more generic variable for this.

2023-08-22 12:13 UTC, JustasVit commented on shop-ui/src/main/frontend/src/app/shared/models/productDto.interface.ts
> +    description: string;
Shouldn't description be optional? In this case, if the description is missing, show different text in UI accordingly.

2023-08-22 12:37 UTC, ArnasPetraitis requested changes

2023-08-22 12:37 UTC, ArnasPetraitis commented on shop-ui/src/main/frontend/src/app/components/product-sort/product-sort.component.less
> +    background: @color-white;
`@color-white` is just a bit better than `#ffffff`. it only alows nice transition to different shade. `@primary-backgroud-color` is more flexible

2023-08-22 12:37 UTC, ArnasPetraitis commented on shop-ui/src/main/frontend/src/app/components/product-sort/product-sort.component.less
> +    box-shadow: 0 4px 6px @color-shadow-light;
`@color-shadow-light;` 👍

2023-08-23 12:54 UTC, JustasVit commented
Make filtering and sorting logic generic.

2023-08-28 06:39 UTC, JustasVit requested changes

2023-08-28 06:39 UTC, JustasVit commented on shop-ui/src/main/frontend/src/app/components/generic-filter/generic-filter.component.html
> +<mat-sidenav-container class="sidenav-container">
Component naming. Maybe just leave it as filter component?

2023-08-28 06:39 UTC, JustasVit commented on shop-ui/src/main/frontend/src/app/components/generic-sort/generic-sort.component.html
> +<div class="sorting-container">
Component naming

2023-08-28 06:39 UTC, JustasVit commented on shop-ui/src/main/frontend/src/app/components/generic-sort/generic-sort.component.ts
> +  private sortChangedSubject = new Subject<T[]>();
naming

2023-08-28 06:39 UTC, JustasVit commented on shop-ui/src/main/frontend/src/app/components/product-list/product-list.component.ts
> +    //private productService: ProductService,
remove

2023-08-28 06:39 UTC, JustasVit commented on shop-ui/src/main/frontend/src/app/components/product-list/product-list.component.ts
> +  setFilterFields(): void {
No need to have separate functions like setSortConfigs, setSortOptions etc. in your case.

2023-08-28 06:39 UTC, JustasVit commented on shop-ui/src/main/frontend/src/app/components/purchase/purchase.component.html
> +        <form (ngSubmit)="executePurchase()" class="purchase-form">
purchase()

2023-08-28 09:22 UTC, JustasVit approved these changes

2023-08-28 09:26 UTC, merged