Td 8 final
Apozzz/TwoDayIntern pull request #8
Opened 2023-08-28 09:30 UTC by Apozzz

iii. Reporto atsisiuntimas

1. Su parametrais

2. Galbut komponentas galetu būti pritaikytas naudoti su keliais reportais

iv. Pakeisti CSS į SCSS

v. CSS iš npm (bootstrap or etc.)

vi. Localizacijos įjungimas (i18n, EN ir LT)

c. Naujas pakeitimas: Parduotuvės UI suvestinės puslapis

i. Pelnas pagal mėnesį

ii. Naujas back-end api gauti duomenims

2023-08-28 14:19 UTC, JustasVit requested changes

2023-08-28 14:19 UTC, JustasVit commented on shop-ui/src/main/frontend/src/app/components/language/language.component.ts
> +    const savedLanguage = this.localStorageService.get<string>(LOCAL_STORAGE_KEYS.SELECTED_LANGUAGE);
Is it really necessary? Looks like localStorageService basically uses localStorage default functionality. It would be ok if additional logic would be implemented in the service.

2023-08-28 14:19 UTC, JustasVit commented on shop-ui/src/main/frontend/src/app/components/language/language.component.ts
> +    return !!langCode && this.languages.some(lang => lang.code === langCode);
langCode instead of !!langCode

2023-08-28 14:19 UTC, JustasVit commented on shop-ui/src/main/frontend/src/app/components/product-list/product-list.component.html
> -            <p *ngIf="product.quantity <= 0" class="out-of-stock">Out of Stock</p>
i18n

2023-08-28 14:19 UTC, JustasVit commented on shop-ui/src/main/frontend/src/app/components/product-list/product-list.component.html
> -            <p *ngIf="product.quantity <= 0" class="out-of-stock">Out of Stock</p>
check other places also.

2023-08-28 14:19 UTC, JustasVit commented on shop-ui/src/main/frontend/src/app/components/product-list/product-list.component.ts
> +  sortOptions: SortOption[] = this.customTranslationService.translateSortOptions([
check if its possible to translate them directly in template.

2023-08-28 14:19 UTC, JustasVit commented on shop-ui/src/main/frontend/src/app/components/profit-graph/profit-graph.component.ts
> +  @Input() attributes: { attribute: string; label: string; }[] = [];
type

2023-08-28 14:19 UTC, JustasVit commented on shop-ui/src/main/frontend/src/app/components/profit-graph/profit-graph.component.ts
> +
no need to repeat chart in variable beginnings.

2023-08-28 14:19 UTC, JustasVit commented on shop-ui/src/main/frontend/src/app/components/profit-graph/profit-graph.component.ts
> +  private subscriptions = new Subscription();
subscription

2023-08-28 14:19 UTC, JustasVit commented on shop-ui/src/main/frontend/src/app/components/profit-table/profit-table.component.less
> +table {
class is necessary.

2023-08-28 14:19 UTC, JustasVit commented on shop-ui/src/main/frontend/src/app/components/profit/profit.component.less
> +form {
class!

2023-08-28 14:19 UTC, JustasVit commented on shop-ui/src/main/frontend/src/app/components/profit/profit.component.ts
> +  attributeLabel: any[] = [];
using any is bad practice. Try to find exact type

2023-08-28 14:19 UTC, JustasVit commented on shop-ui/src/main/frontend/src/app/components/profit/profit.component.ts
> +    this.setDateValue(savedDate);
this.setDateValue(this.profitService.getSelectedDateByViewMode());

2023-08-28 14:19 UTC, JustasVit commented on shop-ui/src/main/frontend/src/app/components/profit/profit.component.ts
> +    this.unsubscribe$.next();
Make destroy logic consistent.

2023-08-28 14:19 UTC, JustasVit commented on shop-ui/src/main/frontend/src/app/components/profit/profit.component.ts
> +import * as moment from 'moment';
import * from 'moment';

2023-08-28 14:19 UTC, JustasVit commented on shop-ui/src/main/frontend/src/app/components/profit/profit.component.ts
> +  navigateToGraph(date: moment.Moment): void {
date: Moment

2023-08-28 14:19 UTC, JustasVit commented on shop-ui/src/main/frontend/src/app/components/profit/profit.component.ts
> +  chosenYearHandler(selectedDate: moment.Moment, picker: MatDatepicker<moment.Moment>): void {
naming

2023-08-28 14:19 UTC, JustasVit commented on shop-ui/src/main/frontend/src/app/components/profit/profit.component.ts
> +  chosenMonthHandler(selectedDate: moment.Moment, picker: MatDatepicker<moment.Moment>): void {
naming

2023-08-28 14:19 UTC, JustasVit commented on shop-ui/src/main/frontend/src/app/components/report/report.component.less
> +form {
class!

2023-08-28 14:19 UTC, JustasVit commented on shop-ui/src/main/frontend/src/app/components/report/report.component.ts
> +    const selectedDateTime = this.dateTimeControl?.value;
No need for const

2023-08-28 14:19 UTC, JustasVit commented on shop-ui/src/main/frontend/src/app/components/report/report.component.ts
> +    const formattedDate = formatDateForReport(selectedDateTime);
formatting should be generic.

2023-08-28 14:19 UTC, JustasVit commented on shop-ui/src/main/frontend/src/app/components/report/report.component.ts
> +    const reportSubscription = this.reportService.downloadCsvReport(formattedDate).subscribe({
subscriptions.add

2023-08-28 14:19 UTC, JustasVit commented on shop-ui/src/main/frontend/src/app/components/report/report.component.ts
> +    const formattedDate = formatDateForReport(selectedDateTime);
Maybe use date pipe?

2023-08-28 14:19 UTC, JustasVit commented on shop-ui/src/main/frontend/src/app/components/report/report.component.ts
> +    const formattedDate = `${now.getFullYear()}-${this.padNumber(now.getMonth() + 1)}-${this.padNumber(now.getDate())}_${this.padNumber(now.getHours())}-${this.padNumber(now.getMinutes())}`;
?

2023-08-28 14:19 UTC, JustasVit commented on shop-ui/src/main/frontend/src/app/services/line-graph.service.ts
> +  generateDataset(attribute: string, label: string, data: Record<number, PurchaseDto[]>, iterations: number): any {
Needs a type

2023-08-28 14:19 UTC, JustasVit commented on shop-ui/src/main/frontend/src/app/services/line-graph.service.ts
> +    return this.generateDataset(attribute, label, data, 12);
why not use generateDataset() directly?

2023-08-28 14:19 UTC, JustasVit commented on shop-ui/src/main/frontend/src/app/services/local-storage.service.ts
> +export class LocalStorageService {
Check if it's really needed.

2023-08-28 14:19 UTC, JustasVit commented on shop-ui/src/main/frontend/src/app/services/purchase.service.ts
> +export interface PurchaseDto {
separate file

2023-08-28 14:19 UTC, JustasVit commented on shop-ui/src/main/frontend/src/app/services/purchase.service.ts
> +export interface UserDto {
separate file

2023-08-28 14:32 UTC, Apozzz commented on shop-ui/src/main/frontend/src/app/components/product-list/product-list.component.html
> -            <p *ngIf="product.quantity <= 0" class="out-of-stock">Out of Stock</p>
Old changes, new ones did have translations

2023-08-28 14:40 UTC, Apozzz commented on shop-ui/src/main/frontend/src/app/components/profit/profit.component.ts
> +import * as moment from 'moment';
I looked this in ts and if you are importing with * you must set it with 'as' to know how to call it.

2023-08-28 14:43 UTC, Apozzz commented on shop-ui/src/main/frontend/src/app/components/report/report.component.ts
> +    const selectedDateTime = this.dateTimeControl?.value;
I look at this after. And it seems, that this variable is used twice.

```
const selectedDateTime = this.dateTimeControl?.value;

if (!selectedDateTime) {
  this.toastr.error('Please select a date first!', 'Error');
  return;
}

const formattedDate = formatDateForReport(selectedDateTime);
```

2023-08-28 14:46 UTC, Apozzz commented on shop-ui/src/main/frontend/src/app/components/report/report.component.ts
> +    const reportSubscription = this.reportService.downloadCsvReport(formattedDate).subscribe({
```
const reportSubscription = this.reportService.downloadCsvReport(formattedDate).subscribe({
  next: response => {
    this.promptUserToDownloadFile(response);
    this.toastr.success('File downloaded successfully!', 'Success');
  },
  error: error => {
    const errorMessage = error?.message || 'An error occurred while downloading the report. Please try again.';
    this.toastr.error(errorMessage, 'Error');
  },
});

this.subscription.add(reportSubscription);
```

2023-08-29 07:20 UTC, Apozzz commented on shop-ui/src/main/frontend/src/app/components/product-list/product-list.component.html
> -            <p *ngIf="product.quantity <= 0" class="out-of-stock">Out of Stock</p>
This is changed code.

2023-08-29 10:36 UTC, JustasVit approved these changes

2023-08-30 06:12 UTC, merged